MVC_Kitaplık/MVC_Kitaplık/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Kitaplık.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_KitapEntities : DbContext
    {
        public Db_KitapEntities()
            : base("name=Db_KitapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public virtual DbSet<Tbl_Kitap> Tbl_Kitap { get; set; }
    }
}

MVC_Kitaplık/MVC_Kitaplık/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\FIRAT UÇAR\source\repos\MVC_Kitaplık\MVC_Kitaplık\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVC_Kitaplık/MVC_Kitaplık/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVC_Kitaplık/MVC_Kitaplık/Models/Tbl_Kategori.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Kitaplık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kategori()
        {
            this.Tbl_Kitap = new HashSet<Tbl_Kitap>();
        }
    
        public int Id { get; set; }
        public string KategoriAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kitap> Tbl_Kitap { get; set; }
    }
}

MVC_Kitaplık/MVC_Kitaplık/Models/Tbl_Kitap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Kitaplık.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kitap
    {
        public int KitapId { get; set; }
        public string Ad { get; set; }
        public string Sayfa { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
    }
}

MVC_Kitaplık/MVC_Kitaplık/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Kitaplık.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Kitaplık/MVC_Kitaplık/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Kitaplık.Models;

namespace MVC_Kitaplık.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        Db_KitapEntities db = new Db_KitapEntities();
        public ActionResult Index()
        {
            var kitaplar = db.Tbl_Kitap.ToList();
            return View(kitaplar);
        }

        [HttpGet]
        public ActionResult KitapEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KitapEkle(Tbl_Kitap tbl_Kitap)
        {
            
            db.Tbl_Kitap.Add(tbl_Kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapSil(int id)
        {
            var kitap = db.Tbl_Kitap.Find(id);
            db.Tbl_Kitap.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapGetir(int id)
        {
            var kitap = db.Tbl_Kitap.Find(id);
            return View("KitapGetir", kitap);

        }

        public ActionResult KitapGuncelle(Tbl_Kitap t)
        {
            var kitap = db.Tbl_Kitap.Find(t.KitapId);
            kitap.Ad = t.Ad;
            kitap.Yazar = t.Yazar;
            kitap.Sayfa = t.Sayfa;
            kitap.Kategori = t.Kategori;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_Kitaplık/MVC_Kitaplık/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Burası projenin about sayfasıdır.</p>

MVC_Kitaplık/MVC_Kitaplık/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_Kitaplık/MVC_Kitaplık/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_Kitaplık/MVC_Kitaplık/Views/Kitap/Index.cshtml
@using MVC_Kitaplık.Models;
@model List<Tbl_Kitap>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_KitapLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Yazarı</th>
        <th>Sayfa</th>
        <th>Tür</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var x in Model)
    {
<tr>
    <td>@x.KitapId</td>
    <td>@x.Ad</td>
    <td>@x.Yazar</td>
    <td>@x.Sayfa</td>
    <td>@x.Tbl_Kategori.KategoriAd</td>
    <td><a href="/Kitap/Kitapsil/@x.KitapId" class="btn btn-danger">Sil </a></td>
    <td><a href="/Kitap/KitapGetir/@x.KitapId" class="btn btn-warning">Güncelle </a></td>

</tr>
    }
</table>

<a href="/Kitap/KitapEkle" class="btn btn-primary">Yeni Kitap</a>

MVC_Kitaplık/MVC_Kitaplık/Views/Kitap/KitapEkle.cshtml
@model MVC_Kitaplık.Models.Tbl_Kitap

@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/_KitapLayout.cshtml";
}

<h2>KitapEkle</h2>

<br />

<form class="form-group" method="post">
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Ad)
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Yazar)
        @Html.TextBoxFor(x => x.Yazar, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Sayfa)
        @Html.TextBoxFor(x => x.Sayfa, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Kategori)
        @Html.TextBoxFor(x => x.Kategori, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>

MVC_Kitaplık/MVC_Kitaplık/Views/Kitap/KitapGetir.cshtml
@model MVC_Kitaplık.Models.Tbl_Kitap
@{
    ViewBag.Title = "KitapGuncelle";
    Layout = "~/Views/Shared/_KitapLayout.cshtml";
}

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y=>y.KitapId)
        @Html.LabelFor(x => x.Ad)
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Yazar)
        @Html.TextBoxFor(x => x.Yazar, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Sayfa)
        @Html.TextBoxFor(x => x.Sayfa, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Kategori)
        @Html.TextBoxFor(x => x.Kategori, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Güncelle</button>
}

MVC_Kitaplık/MVC_Kitaplık/Views/Shared/_KitapLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Kitaplık</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/Kitap/Index">Kitaplar</a></li>
                <li><a href="#">Kategoriler</a></li>
                <li><a href="#">Yardım</a></li>
                <
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>

MVC_Kitaplık/MVC_Kitaplık/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>